name: Build and run tests

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/build_and_run_tests.yml"
      - "Cargo.toml"
      - "Cargo.lock"
      - "src/**"
      - "!**/*.md"
  pull_request:
    branches:
      - main

jobs:
  build-and-run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache cargo dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache cargo build artifacts
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-target-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-target-

      - name: Build
        env:
          RUSTFLAGS: "-D warnings"
        run: cargo build

      - name: Run tests
        run: cargo test
