name: Deploy web version

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/deploy_web_version.yml"
      - "Cargo.toml"
      - "Cargo.lock"
      - "src/**"
      - "!**/*.md"

jobs:
  deploy-web-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache wasm-pack installation
        uses: actions/cache@v3
        with:
          path: ~/.cargo/bin/wasm-pack
          key: ${{ runner.os }}-wasm-pack-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-wasm-pack-

      - name: Install wasm-pack
        run: |
          if [ ! -f ~/.cargo/bin/wasm-pack ]; then
            cargo install wasm-pack
          fi

      - name: Cache cargo dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache wasm-pack build artifacts
        uses: actions/cache@v3
        with:
          path: ./pkg
          key: ${{ runner.os }}-wasm-pkg-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-wasm-pkg-

      - name: Build
        run: wasm-pack build --target web --release

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./pkg
